name: Auto Sync Fork with Custom Changes

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3 AM UTC
  workflow_dispatch:     # Lets you run manually too

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: false

      - name: Set up Git
        run: |
          git config user.name "younyokel"
          git config user.email "younyokel@gmail.com"

      - name: Add upstream repo
        run: |
          git remote add upstream https://github.com/willmiao/ComfyUI-Lora-Manager.git
          git fetch upstream

      - name: Sync fork's main with upstream
        run: |
          git checkout main
          git merge upstream/main --ff-only || true
          git push origin main

      - name: Rebase your custom branch
        run: |
          git checkout custom/main
          git rebase main || true
          git push origin custom/main --force
