name: Auto Sync Fork

on:
  schedule:
    - cron: '0 19 * * *'  # Runs daily
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: false

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add upstream repo
        run: |
          git remote add upstream https://github.com/willmiao/ComfyUI-Lora-Manager.git
          git fetch upstream

      - name: Sync fork's main with upstream
        run: |
          git checkout main
          git merge upstream/main --ff-only || true
          git push origin main

      - name: Rebase your custom branch
        run: |
          git checkout custom/main
          git rebase main || true
          git push origin custom/main --force
